Sprint#4. Tests of qaScooterOrder and qaScooterFaq
MikeKotal/SprintNumberFour pull request #1
Opened 2023-05-21 12:26 UTC by MikeKotal

Разбил тесты на 2 класса, 1 - FAQ, 2 - Заказ, посчитал это наиболее логичным и удобным для отладки
Для каждой подстраницы вынес элементы и методы работы с ними в отдельные классы

2023-05-21 14:36 UTC, alstafeev requested changes

2023-05-21 14:36 UTC, alstafeev commented on src/test/java/ru/yandex/praktikum/qaScooterPage/QaScooterOrderTest.java
> +    public void checkSuccessOrderButtonUpChrome() {
Надо исправить - одни и те же тесты в разных браузерах (а не отдельный тест для Chrome, отдельный для Firefox)

2023-05-21 14:36 UTC, alstafeev commented on src/test/java/ru/yandex/praktikum/qaScooterPage/QaScooterOrderTest.java
> +    public void checkSuccessOrderButtonDownChrome() {
Надо исправить -  после изменения тестов (один тест на два браузера) надо учесть - два теста для заказа самоката: один начинается с верхней кнопки “Заказать”, второй с нижней. В разных тестах использованы разные данные (параметризация)

2023-05-21 14:36 UTC, alstafeev commented on src/test/java/ru/yandex/praktikum/qaScooterPage/QaScooterPageFaqTest.java
> +        faq.checkQuestions();
Надо исправить - надо проверять текст вопросов, а не только отображение (можно через параметризацию, либо в константах тестового класса, либо в отдельном файле)

2023-05-21 19:48 UTC, MikeKotal commented on src/test/java/ru/yandex/praktikum/qaScooterPage/QaScooterOrderTest.java
> +    public void checkSuccessOrderButtonDownChrome() {
Могу ли я разбить в таком случае тестирование заказа на 2 класса, для каждой кнопки по одному, поскольку я не нашел в junit4 способа использовать в одном классе, для каждого теста уникальные тестовые данные через один раннер, такое возможно с testNG и дата провайдером, либо junit5 с его параметризацией, я бы не хотел применять ради одного теста эти фремворки

2023-05-22 18:46 UTC, MikeKotal commented on src/test/java/ru/yandex/praktikum/qaScooterPage/QaScooterOrderTest.java
> +    public void checkSuccessOrderButtonUpChrome() {
Исправлено

2023-05-22 18:47 UTC, MikeKotal commented on src/test/java/ru/yandex/praktikum/qaScooterPage/QaScooterPageFaqTest.java
> +        faq.checkQuestions();
Добавил новую функциональность по проверке текста вопроса и ответа, а так же убрал разделение тестов по браузеру

2023-05-23 11:25 UTC, alstafeev approved these changes

2023-05-23 11:25 UTC, alstafeev commented on src/test/java/ru/yandex/praktikum/qaScooterPage/QaScooterOrderTestButtonDown.java
> +        if (browser.equals("Chrome")) {
Можно лучше - в идеале вынести инициализацию веб драйвера в базовый класс, в @Before 
Чтобы инициализация не происходила в тесте

2023-05-23 19:08 UTC, merged